# ===================================================================
# Spring Boot configuration for the "demo" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate.SQL: DEBUG

server:
  application:
    name: MetaSystem (Demo mode)
  address: 0.0.0.0
  port: 9294
  contextPath: /metasystem

spring:
  datasource:
    url: jdbc:h2:mem:grouse;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: db/import.sql
        show_sql: true
        hbm2ddl.auto: create-drop
